services:
  doc_weaviate:
    build: ./weaviate
    image: doc_weaviate:latest
    container_name: doc_weaviate
    ports:
    - 8083:8083
    - 50053:50053
    volumes:
    - data:/var/lib/weaviate
    restart: on-failure:0

  doc_backend:
    build: ./backend
    image: doc_backend:latest
    container_name: doc_backend
    volumes:
      - ./backend:/app
    ports:
      - "8003:8003"
    depends_on:
      - doc_weaviate
    env_file:
      - .env

  doc_frontend:
    build: ./frontend
    image: doc_frontend:latest
    container_name: doc_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3003:3003"
    depends_on:
      - doc_backend
    stdin_open: true
    tty: true

volumes:
  data:
